version: '2.3'
networks:
  log4pot_local:
services:
  log4pot:
#    build: .
    container_name: log4pot
    restart: always
    tmpfs:
     - /tmp:uid=2000,gid=2000
    networks:
     - log4pot_local
    ports:
     - "80:8080"
     - "443:8080"
     - "8080:8080"
     - "9200:8080"
     - "25565:8080"
    image: "ghcr.io/goffinet/log4pot-container:master"
    read_only: true
    volumes:
     - "$PWD:/opt/Log4Pot"
